version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./vector_store:/app/vector_store
    working_dir: /app
    tty: true